@ECHO OFF
SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION

SET LIB_DIR=lib/
SET CLASSPATH=classes/
SET MAIN_CLASS=org.jasig.irclog.IrcLogger

FOR %%f IN (%LIB_DIR%*.jar) DO (
    SET CLASSPATH=!CLASSPATH!;%LIB_DIR%%%f
)

ECHO Using CLASSPATH:     %CLASSPATH%
ECHO Using MAIN_CLASS:    %MAIN_CLASS%

java -cp %CLASSPATH% %MAIN_CLASS% %*

ENDLOCAL